response to shutdown signal
mtlynch/picoshare pull request #398
Opened 2023-02-14 07:12 UTC by phosae

2023-02-14 07:19 UTC, phosae commented
I have read the CLA Document and I hereby sign the CLA

2023-02-14 07:27 UTC, phosae commented
/cc @mtlynch

2023-02-16 01:46 UTC, mtlynch requested changes
Awesome, thanks! Just a few minor questions.

2023-02-16 01:46 UTC, mtlynch commented on cmd/picoshare/main.go
> +	httpSrv := &http.Server{Addr: fmt.Sprintf(":%s", port), Handler: h}
Why `&http.Server` instead of just `http.Server`?

2023-02-16 01:46 UTC, mtlynch commented on cmd/picoshare/main.go
> +func setupSignalHandler() (stopCh <-chan struct{}) {
Can we delete the name `stopCh`? The rest of the code doesn't use named returns, and we don't use `stopCh` in this function.

2023-02-17 00:26 UTC, mtlynch approved these changes
LGTM, thanks!

2023-02-17 00:26 UTC, merged