Make Litestream retention configurable
mtlynch/picoshare pull request #447
Opened 2023-07-18 05:58 UTC by ribtoks

Details in #446 

One problem though: due to current code organization (few "entrypoints"), I did not find a good **single** place for a default value.

2023-07-18 06:00 UTC, ribtoks commented
I have read the CLA Document and I hereby sign the CLA

2023-07-18 06:00 UTC, ribtoks commented
recheck

2023-07-19 01:26 UTC, mtlynch requested changes
>I have read the CLA Document and I hereby sign the CLA

It looks like the email address you're using for commits (the `@mailbox.org` address) isn't associated with your Github account, so CLAbot won't accept your signature.

Can you add the email address to your account? Or add a commit using an email address that's already associated with your Github account?

https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

2023-07-19 01:26 UTC, mtlynch commented on README.md
> +LITESTREAM_RETENTION="72h" # optional
We can omit this here, since I want to limit it to the simplest set of options.

2023-07-19 01:26 UTC, mtlynch commented on README.md
> +| `LITESTREAM_RETENTION`         | The amount of time Litestream snapshots & WAL files will be kept. (default 72h)                       |
Can we say "(defaults to 72h)." to match the conventions above?

(add 'to' and period after parens)

2023-07-19 01:26 UTC, mtlynch commented on dev-scripts/serve-docker
> +LITESTREAM_RETENTION=${LITESTREAM_RETENTION:-72h}
We can skip the retention setting in this file, as this script is just for development.

2023-07-19 01:26 UTC, mtlynch commented on docs/deployment/fly.io.md
> +Additionally you can set up "retention" (see [Litestream replica settings](https://litestream.io/reference/config/#replica-settings)) for how long snapshots will be kept, using `LITESTREAM_RETENTION`
We can leave out the documentation here for simplicity. Otherwise, we end up redundantly defining every env variable in every deployment doc.

2023-07-19 05:29 UTC, ribtoks commented
recheck

2023-07-19 05:40 UTC, ribtoks commented
e2e tests are a bit flaky, I had to bump the playwright timeout

2023-07-19 12:48 UTC, mtlynch approved these changes
LGTM, thanks for implementing this!

2023-07-19 12:49 UTC, merged